server:
  port: 8002
spring:
  application:
    name: crowd-mysql
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: 'jdbc:mysql://localhost:3306/project_crowd?useUnicode=true&characterEncoding=UTF-8'
    username: root
    password: 'SAIERHAO123'
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka
logging:
  level:
    com.crux.crowd.member.mapper: debug
    com.crux.crowd.member.test: debug
