server:
  port: 80
spring:
  application:
    name: crowd-gateway
  redis:
    host: 192.168.153.200
    timeout: 1800s
  session:
    store-type: redis
zuul:
  routes:
    mysql:
      service-id: crowd-mysql
      path: /mysql/**
    authenticaton:
      service-id: crowd-authentication
      path: /**
  ignored-services: '*'
  # 由于Session使用Cookie，必须设置此项。否则转发请求时请求头中的设置项会被拦截，导致session不能共享
  # 默认拦截Cookie, Set-Cookie, Authorization
  sensitive-headers: []
  host:
    connect-timeout-millis: 10000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka
crowd:
  login:
    release-path:
      - "/index.html"
      - "/member/register.html"
      - "/member/register/**"
      - "/member/login.html"
      - "/member/login/**"
      - "/member/logout.html"