server:
  port: 80
spring:
  application:
    name: crowd-gateway
  redis:
    host: 192.168.153.200
    timeout: 1800s
  session:
    store-type: redis
zuul:
  routes:
    # 支付系统网关
    pay:
      service-id: crowd-pay
      path: /pay/**
    # 订单系统网关
    order:
      service-id: crowd-order
      path: /order/**
    # 项目系统网关
    project:
      service-id: crowd-project
      path: /project/**
    # 会员系统网关
    authenticaton:
      service-id: crowd-authentication
      path: /**
  ignored-services: '*'
  # 由于Session使用Cookie，必须设置此项。否则转发请求时请求头中的设置项会被拦截，导致session不能共享
  # 默认拦截Cookie, Set-Cookie, Authorization
  sensitive-headers: []
# Zuul的超时时间通过ribbon设置
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 10000
  MaxAutoRetries: 2
  MaxAutoRetriesNextServer: 1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka
crowd:
  login:
    release-path:
      - "/index.html"
      - "/member/register.html"
      - "/member/register/**"
      - "/member/login.html"
      - "/member/login/**"
      - "/member/logout.html"
      - "/project/detail/*"