server:
  port: 80
spring:
  application:
    name: crowd-gateway
  cloud:
    gateway:
      discovery:
        locator:
          # 通过注册中心服务名创建路由
          enabled: true
      # 路由（routes：路由，它由唯一标识（ID）、目标服务地址（uri）、一组断言（predicates）和一组过滤器组成（filters）。filters 不是必需参数。）
      routes:
        # 路由标识（id：标识，具有唯一性）综合
        - id: crowd-authenticaton
          # 目标服务地址（uri：地址，请求转发后的地址）
          # lb://服务名。使用负载均衡转发
          uri: lb://crowd-authentication
          # 路由条件（predicates：断言，匹配 HTTP 请求内容)
          # 当下边的条件符合规则时，放行。否则404
          predicates:
            # 路径规则。等同zuul的path
            - Path=/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka
