server:
  port: 8011
spring:
  application:
    name: crowd-project
  mvc:
    static-path-pattern: /static/**
    hiddenmethod:
      filter:
        enabled: true
  redis:
    host: 192.168.153.200
    timeout: 1800s
  session:
    store-type: redis
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka
aliyun:
  oss:
    access-key-id: key
    access-key-secret: secret
    bucket-name: name
    bucket-domain: domain
    endpoint: endpoint
