server:
  port: 8013
spring:
  application:
    name: crowd-pay
  mvc:
    static-path-pattern: /static/**
    hiddenmethod:
      filter:
        enabled: true
  redis:
    host: 192.168.153.200
    timeout: 1800s
  session:
    store-type: redis
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka
alipay:
  config:
    app-id: 你的appid
    merchant-private-key: 你的私钥
    alipay-public-key: 支付宝公钥
    gateway-url: 支付宝网关
    return-url: http://qghprk.natappfree.cc/pay/alipay/return
    notify-url: http://qghprk.natappfree.cc/pay/alipay/notify
