server:
  port: 8013
spring:
  application:
    name: crowd-pay
  mvc:
    static-path-pattern: /static/**
    hiddenmethod:
      filter:
        enabled: true
  redis:
    host: 192.168.153.200
    timeout: 1800s
  session:
    store-type: redis
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka
alipay:
  config:
    app-id: 2021000119667895
    merchant-private-key: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDFytWTxFpXE4LH9tA+APFzA8JEWGqS3+9RdLWgyjQuj5TML0GAl82YOxNQD0eNX5m/ylTbmDfx6hf32/jPRIehYk7dbTdWuoBD4bkCdqcOR6Hni6xzwJk+Z2Nq5Vo5xdEQKpoNStXdhVCHd2Qkb66Q4Hl2W32w+o1ASTVbeyx15zm8slCSnTnbYDFjy06qKHpaoQOKO3/iQNQaZIXgrZgE/G+hpDWmjc+egS7jAPT7KhGlvZvpB1YgatGuvj65uwtG3pI4rB5qj+S63ALOD41Lh2KIOHbMeUQWrR8DSqmEoTUYy49v5QRVupkayoD+9/cWJY3znZ9l2iRH8LN4wwI3AgMBAAECggEBAIoJEV6rtMR6SFYXSKNM8zRqViRudAoGoDT/t1X8Z8hqydRp0lPVHVV1PPgtgakHI/y2Ttxl8f0xewKukIjN8b3OJu3fL7SmOaemGwC+H74WfcZjMrohmpDzhG1wnLQe+tVGdfZ62KBdTqMLzmajTnerQPk5xpFBelx3+vXaE2BAAKSUZHkfWEcoYT4wNPIeM0NK9vXsRll7dIby116ylYOorWRUmI3gGg8v9HGvoaVHkEoYesZ/8abyOr6aH8zSZ/calbdSYbidn7lqonJVOtgKCs1f9qTSXQybiIRz9KqyAGD8Uo2z5jy4K0iR+xqGdrXMBHT1ovSSuCINanutckkCgYEA8dX7/2/AGU60mbDCVHe8H9ByinNpmWfEuQO3OOX1ocMNEdbPLdxocmys/A7hj5jJA7fg0LlnIew2wn//2Eq/smJBGl++hiMiRmfP4X2pJqE/nUzbWGg15A9KVsIUrB3yjJl0vh40whN+ozRXnGgS3I9IThAnyHa12Gbv73jdYpUCgYEA0WB5UAOMYSILkNs7VbLPuuvOlHz3xQIpl3CSYzKDDkvXTbvdgVju1Kj6ENgkGffF+BXJ6j1Rc0BpW5XoJcTnUORJkovwFGt0n9AjOwn//7mmpOlFSSCrzwnlUHUgyARL0+MbCrw3xJBp9V6yrj+xU/mnTshojtAUO+lM87REipsCgYEAv64067S+lRCOExdIID07LhhBAT4TIBVglqi8S+vxMkLwlAgn9JizbKZ4wdxlqjSWd00Cc03Q0dFxYd6kgeJVaOV55pam45jrbNSRr4+zR7wdOOeXH86RkG8SJAv26Klf+1MSdjJo7L8Y6/Dr1DulX45t5/nkHn8BCUIlwTCSgLUCgYBQ1nWgDe6qJfHfOLWc7c/ENHzq2aDz4FTckmsCf6MX5vI2ofzwjryPQLpjvH+bww0dLpRpqskCvXCwGp2pz28bzTgWq47C44YAmeSwS7kaK7yKWUIV7NZItmJiAQbqEraQFVQAfhDuBG/Ue35zRkYZzP7qrPepg+77/qRmR0hbVwKBgQCnriZOQ7Qh/BsFT88BN0BVYB2rMblzerXBdhyThDE8u0xuDvCoSpEfJuSdPN1KpDxQGVLrx04qxve9yK7q8AEDFCgTNzUonUIbII5Hp+tvjIlRn/oNiRZ7ZPs4oYtnnJSQve4O9uvURtT7uXVcXfhvX5MZ621TcGJomc5tMasoVA==
    alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAk6Zw43VecTzJO1Bbx7nAO5I+y13JFby0TR7XW1Wc+GltHU7nHGYnZYsjj8xDCqyJCNQN+h9ml0CSDH11Rz9z/wZtq0bDUD3fPjQmif5j/eOX7T3c2MdT6rrP0ik4hSf97SSV0ECgwYyV8o1hg41Ce2gWa+L9jrLgL9SvZAAxalsCH78s+77HbcMrDFCZn06aXBa77zdo2BrrYMh8+wTzNAsVIcGjsvLJZJHJkHNz6Gx/pLZdDTsgvVKbdBFTLOKQ3chE/5F2JuAf6ihiy4HSVsw/ZlCflSNzBdOIEP6WW9R0DuneYJ/G3M4fcnyAXgWFiGuFqzyELVwbULTkFX7ZCQIDAQAB
    gateway-url: https://openapi.alipaydev.com/gateway.do
    return-url: http://viuzzt.natappfree.cc/pay/alipay/return
    notify-url: http://viuzzt.natappfree.cc/pay/alipay/notify