server:
  port: 8010
spring:
  application:
    name: crowd-authentication
  mvc:
    # 静态资源前缀
    static-path-pattern: /static/**
    # 开启hiddenMethodFilter
    hiddenmethod:
      filter:
        enabled: true
  redis:
    host: 192.168.153.200
    timeout: 1800s
  session:
    store-type: redis
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka
crowd:
  message-api:
    host: https://gyytz.market.alicloudapi.com
    path: /sms/smsSend
    method: POST
    headers:
      Authorization: 'APPCODE e5d453c148934283923555adbeb4c91b'
    mobile-name: mobile
    param:
      param-name: param
      code-prefix: '**code**:'
      minute-prefix: '**minute**:'
    sign:
      smsSignId: 2e65b1bb3d054466b82f0c9d125465e2
    template:
      templateId: 908e94ccf08b4476ba6c876d13f084ad
  oss-api:
    access-key:
      secret: lX7iDvm3kzs9EQGUAsgYTRONtou4pO